# Generated by Django 5.0.6 on 2024-06-18 05:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('project_type', models.CharField(choices=[('Tech', 'Tech'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Other', 'Other')], max_length=50)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('Timeline', models.DateField()),
                ('lead_files', models.FileField(blank=True, null=True, upload_to='lead_files/')),
                ('budget', models.CharField(max_length=100)),
            ],
        ),
    ]
