# Generated by Django 5.0.6 on 2024-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0031_superadmin_last_login_alter_project_employees_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='superadmin',
        #     name='last_login',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        # ),
    ]
