# Generated by Django 5.0.6 on 2024-07-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_alter_project_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
