# Generated by Django 5.0.6 on 2024-07-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0037_alter_superadmin_options_remove_superadmin_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='last_login',
        ),
    ]
