# Generated by Django 5.0.6 on 2024-07-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0043_employee_total_leaves_employee_used_leaves_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='employee',
        #     name='total_leaves',
        # ),
        # migrations.RemoveField(
        #     model_name='employee',
        #     name='used_leaves',
        # ),
    ]
