# Generated by Django 5.0.6 on 2024-07-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0046_remove_employee_total_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
    ]
