# Generated by Django 5.0.6 on 2024-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0052_alter_taskfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('inprogress', 'inprogress'), ('Completed', 'Completed')], default='inprogress', max_length=50),
        ),
    ]
