# Generated by Django 5.0.6 on 2024-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0053_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='hours',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
