# Generated by Django 5.0.6 on 2024-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0056_alter_salaryslip_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
