# Generated by Django 5.0.6 on 2024-06-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
