# Generated by Django 5.0.6 on 2024-06-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
