# Generated by Django 5.0.6 on 2024-06-26 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
