# Generated by Django 5.0.6 on 2024-06-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
