# Generated by Django 5.0.6 on 2024-06-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_project_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(related_name='employee', to='superadmin.project'),
        ),
    ]
