# Generated by Django 5.0.6 on 2024-06-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_remove_employee_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_to',
        ),
    ]
