# Generated by Django 5.0.6 on 2024-06-20 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_projectfile'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Board',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=255)),
        #         ('description', models.TextField()),
        #     ],
        # ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('todo', 'To Do'), ('inprogress', 'In Progress'), ('inreview', 'In Review'), ('completed', 'Completed')], default='inprogress', max_length=50),
        ),
        # migrations.AddField(
        #     model_name='task',
        #     name='board',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superadmin.board'),
        #     preserve_default=False,
        # ),
    ]
