# Generated by Django 5.0.6 on 2024-06-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_remove_task_board'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='task',
        #     name='board',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superadmin.board'),
        #     preserve_default=False,
        # ),
    ]
