# Generated by Django 5.0.6 on 2024-06-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_task_board'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='task',
        #     name='board',
        # ),
        # migrations.DeleteModel(
        #     name='Board',
        # ),
    ]
