# Generated by Django 5.0.6 on 2024-06-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_initial'),
        ('superadmin', '0020_alter_board_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAdmin',
            fields=[
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.leave')),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
