# Generated by Django 5.0.6 on 2024-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0024_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
