# Generated by Django 5.0.6 on 2024-07-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0025_invoiceitem_quantity_invoiceitem_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
    ]
