# Generated by Django 5.0.6 on 2024-07-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0026_remove_invoiceitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
