# Generated by Django 5.0.6 on 2024-07-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0029_contacts_ifsc_code_contacts_swift_code_contacts_bank_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Superadmin',
        ),
    ]
