# Generated by Django 5.0.6 on 2024-07-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0030_rename_contacts_superadmin'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='superadmin',
        #     name='last_login',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        # ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='employees',
        #     field=models.ManyToManyField(related_name='projects', to='superadmin.employee'),
        # ),
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.employee'),
        ),
    ]
