# Generated by Django 5.0.6 on 2024-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0032_superadmin_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={'verbose_name': 'superadmin', 'verbose_name_plural': 'superadmins'},
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
