# Generated by Django 5.0.6 on 2024-07-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0033_alter_superadmin_options_superadmin_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superadmin',
            old_name='company',
            new_name='company_name',
        ),
    ]
