# Generated by Django 5.0.6 on 2024-07-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0036_superadmin_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={},
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_superuser',
        ),
        # migrations.RemoveField(
        #     model_name='superadmin',
        #     name='last_login',
        # ),
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
