# Generated by Django 5.0.6 on 2024-07-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('superadmin', '0038_remove_superadmin_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='groups',
            field=models.ManyToManyField(related_name='superadmin_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='user_permissions',
            field=models.ManyToManyField(related_name='superadmin_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(related_name='employee_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(related_name='employee_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
