# Generated by Django 5.0.6 on 2024-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0041_alter_employee_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
