# Generated by Django 5.0.6 on 2024-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0042_alter_superadmin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='used_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
