# Generated by Django 5.0.6 on 2024-07-08 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0047_employee_total_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_files',
        ),
        migrations.CreateModel(
            name='LeadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_files/')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='superadmin.lead')),
            ],
        ),
    ]
