# Generated by Django 5.0.6 on 2024-07-08 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0049_remove_client_img_clientimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='img',
        ),
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_images/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='superadmin.employee')),
            ],
        ),
    ]
