# Generated by Django 5.0.6 on 2024-07-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0055_salaryslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.employee'),
        ),
    ]
