# Generated by Django 5.0.6 on 2024-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0062_alter_board_name_alter_changerequest_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
