# Generated by Django 5.0.6 on 2024-07-24 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_leave_end_date_leave_start_date'),
        ('superadmin', '0053_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.employee'),
        ),
    ]
